### PR TITLE
Version 1.74.5

### PR DESCRIPTION
**Pull request by Memendia**
Tweaks the -engine command to be more "Module"
Adds 2 new commands "-telsa" and "-hail"

Tesla being the same as -sing but for the Tesla Engine

Hail removes the mostly unused -law command and replaces it with a message for our Lord and Savior - Dr. Bronzebeard

Happy?

### CODE REVIEW

**Comment by Memendia** [comment]
@GunHog Tada

**Comment by GunHog** [comment]
Add the changelog to the manual. Later I will have to make it a separate file or something.

**Comment by Memendia** [comment]
Was just going to do that

**Comment by Memendia** [comment]
@GunHog updooted

**Comment by GunHog** [comment]
Good girl.

**Pull request merged**
